name: Update Submodules and Deploy

on:
  repository_dispatch:
    types: [submodule_updated]

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update submodules
      run: |
        git submodule update --remote
        git commit -am "Submodule updated!"
        git push

  build_and_deploy:
    needs: update_submodules
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
